<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/07/12 10:54:44

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
