<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/07/13 19:21:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
