<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/07/13 17:27:20
sfConfig::add(array(
  'mod_jobeet_category_enabled' => true,
  'mod_jobeet_category_view_class' => 'sfPHP',
));
