generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JobeetJob
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jobeet_job
    with_doctrine_route:   true
    #actions_base_class:    sfActions

    config:
      actions: ~ #~ means that symfony can setup the action automatically
      fields: #this section override all view (new, list and edit) field configuration
        is_activated: { label: Activated?, help: Whether the use has activated the job, or not }
        is_public:    { label: Public?, help: Whether the job can also be published on affiliate websites, or not }
      list:
        title:   Job Management
        layout:  stacked
        display: [company, position, location, url, is_activated, email]
        params:  |
          %%is_activated%% <small>%%jobeet_category%%</small> - %%company%%
           (<em>%%email%%</em>) is looking for a %%=position%% (%%location%%)
        sort: [expires_at, desc]
        max_per_page: 10
        batch_actions:
          _delete:    ~
          extend:     ~
        object_actions:
          extend:     ~
          _edit:      ~
          _delete:    ~
        actions:
          deleteNeverActivated: { label: Delete never activated jobs }
        table_method: retrieveBackendJobList #reduce the sql request number
      filter:
        display: [category_id, company, position, description, is_activated, is_public, email, expires_at]
      form:
        class: BackendJobeetJobForm
        display:
          Content: [category_id, type, company, logo, url, position, location, description, how_to_apply, is_public, email]
          Admin:   [ _generated_token, is_activated, expires_at]
      edit:
        title: Editing Job "%%company%% is looking fo a %%position%%"
      new:
        title: Job Creation
