<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/07/14 09:59:30
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
